"""empty message

Revision ID: 07ff0c6a9768
Revises: 5167a1cb9d6e
Create Date: 2022-04-08 20:06:55.713025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ff0c6a9768'
down_revision = '5167a1cb9d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
